export const ADD_FORM_LIST = "ADD_FORM_LIST";
export const CLEAR_FORM_LIST = "CLEAR_FORM_LIST";
export const ADD_FORM_DETAILS = "ADD_FORM_DETAILS";

export const ADD_FILL_LIST = "ADD_FILL_LIST";
export const CLEAR_FILL_LIST = "CLEAR_FILL_LIST";
export const SET_ALL_FILLS_LOADED = "SET_ALL_FILLS_LOADED";

export const SHOW_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const ADD_FORM = "ADD_FORM";
export const CLEAR_FORM = "CLEAR_FORM";

export const SAVE_FORM_DRAFT = "SAVE_FORM_DRAFT";
export const CREATE_FORM_DRAFT = "CREATE_FORM_DRAFT";
export const CLEAR_FORM_DRAFT = "CLEAR_FORM_DRAFT";
